# Map ctrl -> F18, alt -> F19, cmd -> F20
remap_keys:
  - from: '<ctrl_l>'
    to: '<f18>'
  - from: '<ctrl_r>'
    to: '<f18>'
  - from: '<cmd_l>'
    to: '<f19>'
  - from: '<cmd_r>'
    to: '<f19>'
  - from: '<alt_l>'
    to: '<f17>'
  - from: '<alt_r>'
    to: '<f17>'

passthrough_hotkeys:
  - '<ctrl>+<alt>+<shift>+q'
  - '<ctrl>+<alt>+<shift>+z'
  - '<ctrl>+<alt>+<shift>+x'
  - '<ctrl>+<alt>+<shift>+s'
  - '<ctrl>+<alt>+<shift>+m'
  - '<cmd>+q'
  - '<cmd>+<tab>'

mode: 'client'