# F17 -> Ctrl
# F18 -> Windows Key
# F19 -> Alt
remap_keys:
  - from: '<ctrl_l>'
    to: '<f17>'
  - from: '<ctrl_r>'
    to: '<f17>'
  - from: '<cmd_l>'
    to: '<f19>'
  - from: '<cmd_r>'
    to: '<f19>'
  - from: '<alt_l>'
    to: '<f18>'
  - from: '<alt_r>'
    to: '<f17>' # For Magic Keyboard, map right alt to f17 (ctrl)

passthrough_hotkeys:
  - '<ctrl>+<alt>+<shift>+q'
  - '<ctrl>+<alt>+<shift>+z'
  - '<ctrl>+<alt>+<shift>+x'
  - '<ctrl>+<alt>+<shift>+s'
  - '<ctrl>+1'
  - '<ctrl>+2'
  - '<ctrl>+3'
  - '<ctrl>+4'
  - '<ctrl>+5'
  - '<ctrl>+6'
  - '<ctrl>+7'
  - '<ctrl>+8'
  - '<ctrl>+9'
  - '<ctrl>+0'
