# F17 -> Ctrl
# F18 -> Windows Key
# F19 -> Alt
remap_keys:
  - from: '<ctrl_l>'
    to: '<f17>'
  - from: '<ctrl_r>'
    to: '<f17>'
  - from: '<cmd_l>'
    to: '<f19>'
  - from: '<cmd_r>'
    to: '<f19>'
  - from: '<alt_l>'
    to: '<f18>'
  - from: '<alt_r>'
    to: '<f17>' # For Magic Keyboard, map right alt to f17 (ctrl)

passthrough_hotkeys:
  - '<ctrl>+<alt>+<shift>+q'
  - '<ctrl>+<alt>+<shift>+z'
  - '<ctrl>+<alt>+<shift>+x'
  - '<ctrl>+<alt>+<shift>+s'
  - '<ctrl>+<alt>+<shift>+m'
  # Our hotkey parsing routine maps 0..9 keys to the numpad keycodes, not the regular num keycodes.
  # Specify the keycodes of the regular num keys to workaround the issue.
  - '<ctrl>+<18>' # 1
  - '<ctrl>+<19>' # 2
  - '<ctrl>+<20>' # 3
  - '<ctrl>+<21>' # 4
  - '<ctrl>+<23>' # 5
  - '<ctrl>+<22>' # 6
  - '<ctrl>+<26>' # 7
  - '<ctrl>+<28>' # 8
  - '<ctrl>+<25>' # 9
  - '<ctrl>+<29>' # 0
